---
- summary: | # № 2 
    Лишняя кнопка перехода на предыдущую страницу на первой странице каталога товаров
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    Открыть главную страницу магазина
  expected-result: |
    Отображается только кнопка перехода на следующую страницу каталога товаров
  actual-result: |
    Отображаются кнопки перехода на следующую и предыдущую страницы каталога товаров (см. скриншот ТК2 1 версия сайта.png)

- summary: | # № 3 
    Лишняя кнопка перехода на следующую страницу на последней странице каталога товаров
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    Открыть последнюю страницу каталога товаров
  expected-result: |
    Отображается только кнопка перехода на предыдущую страницу каталога товаров
  actual-result: |
    Отображаются кнопки перехода на следующую и предыдущую страницы каталога товаров (см. скриншот ТК3 1 версия сайта.png)

- summary: | # № 7 
    Сбивается отображение товаров при переходе с последней страницы каталога на предыдущую
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть последнюю страницу каталога товаров
    - Перейти на предыдущую страницу каталога товаров
  expected-result: |
    Отображаются все товары (30 товаров) предыдущей страницы каталога
  actual-result: |
    Отображаются только 20 товаров: 10 товаров последней страницы каталога, 10 товаров предыдущей страницы

- summary: | # № 8 
    В каталоге товаров не отображается рейтинг у товаров
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce: |
    Открыть главную страницу магазина
  expected-result: |
    У товаров каталога отображается информация - название, рейтинг, цена и цена со скидкой
  actual-result: |
    У товаров каталога отображается информация - название, цена и цена со скидкой, но не отображается рейтинг (см. скриншот ТК8 1 версия сайта.png)

- summary: | # № 10 
    Несоответствие информации о товаре в каталоге и на странице товара из-за отсутствия отображения рейтинга у товара в каталоге
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть главную страницу магазина
    - Перейти на страницу товара "MacBook Pro"
  expected-result: |
    Информация о товаре на странице каталога совпадает с информацией на странице товара (название, рейтинг, цена и цена со скидкой)
  actual-result: |
    1. Информация о товаре на странице каталога совпадает с информацией на странице товара (название, цена и цена со скидкой)
    2. Рейтинг отображается только на странице товара

- summary: | # № 16 
    Нет "пустой" категории в фильтре
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть последнюю страницу каталога
    - В фильтр выбрать категорию "motorcycle "
  expected-result: |
    1. Выбрать в фильтре "пустую" категорию товаров
    2. Отображаются все товары открытой страницы каталога
  actual-result: |
    Нет "пустой" категории в фильтре

- summary: | # № 22 
    Отображается уведомление об отсутствии товаров при сбросе "В наличии" в фильтре
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть главную страницу магазина
    - Сбросить в фильтре "В наличии"
  expected-result: |
    Отображаются товары открытой страницы каталога имеющиеся и отсутствующие в наличии
  actual-result: |
    Отображается уведомление об отсутствии товаров (см. скриншот ТК22 1 версия сайта.png)

- summary: | # № 59 
    После оформления заказа не переходит на страницу оплаты
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть главную страницу магазина
    - Добавить товар "Key Holder" в корзину
    - Перейти в корзину
    - Оформить заказ
  expected-result: |
    Открылась страница оплаты
  actual-result: |
    1. Страница оплаты не открылась
    2. На странице корзины появилось модальное окно с уведомлением об успешном оформлении заказа (см. скриншот ТК59 1 версия сайта.png)

- summary: | # № 60 
    Товары в корзине не хранятся в сессии браузера
  environment: |
    Google Chrome   118.0.5993.118 (Официальная сборка) (64 бит)
    ОС Windows 10 Pro
  steps-to-reproduce:
    - Открыть главную страницу магазина
    - Добавить товар "Huawei P30" в корзину
    - Закрыть вкладку в браузере с сайтом
    - Открыть сайт в новой вкладке браузера
    - Перейти в корзину
  expected-result: |
    В корзине отображается добавленный товар "Huawei P30"
  actual-result: |
    В корзине отсутствует товар (корзина пустая)
