---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность убрать выбранный фильтр
  - Пользователь должен иметь выбор кол-ва добавляемого в корзину товара
  - Пользователь должен иметь возможность редактировать кол-во добавленного товара в корзине
  - Пользователь должен иметь возможность выбора страницы каталога товаров
  - Пользователь должен иметь возможность удаления товара из корзины
  - Пользователь не должен иметь возможность заказать кол-во товара больше чем есть в наличии
  - Во время удаления товара из корзины должно появляться всплывающее окно с подтверждением выполняемого действия
  - Пользователь должен иметь возможность очистки корзины
  - Во время очистки корзины должно появляться всплывающее окно с подтверждением выполняемого действия
  - При добавлении товара пользователь должен получать уведомление об успешном добавлении товара
  - При добавлении товара в корзине должен увеличиваться счетчик
  - В корзине должна корректно рассчитываться сумма заказа
  - Цена товара со скидкой должна быть меньше цены товара без скидки
  - Пользователь должен иметь возможность перейти с товара добавленного в корзине в карточку товара в каталоге
  - После оформления заказа пользователь должен получать уведомление об успешном оформлении заказа
  - После оформления заказа корзина должна самоочищаться
