---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность регистрации на сайте или иметь возможность предоставления контактной информации о себе продавцу
  - Пользователь должен иметь возможность убрать выбранные значения в фильтрах
  - Сайт должен запоминать выбранные пользователем значения в фильтрах
  - Пользователь должен иметь возможность оценить товар
  - Пользователь должен иметь возможность выбора количества товара, добавляемого в корзину и удаляемого из нее
  - Пользователь не должен иметь возможности заказа товара в количестве большем, чем есть в наличии
  - Во время удаления товара из корзины и очистки корзины должно появляться уведомление с подтверждением выполняемого действия или возможностью отмены действия
  - После оформления заказа корзина должна самоочищаться
