---
- summary: | # № 1
    Проверка поиска существующих товаров по ключевому слову
  status: pass

- summary: | # № 2
    Проверка поиска несуществующих товаров по ключевому слову
status: pass

- summary: | # № 3 
    Проверка отмены поиска товаров по ключевому слову
status: pass

- summary: | # № 4 
    Проверка работы фильтра по категории товаров
status: pass

- summary: | # № 5 
    Проверка работы фильтра по бренду товаров
status: pass

 - summary: | # № 6 
    Проверка работы фильтра по бренду товаров по нескольким брендам
status: pass

- summary: | # № 7 
    Проверка сброса фильтра по бренду товаров
status: pass

- summary: | # № 8 
    Проверка сброса бренда из фильтра по бренду товаров
status: pass

- summary: | # № 9 
    Проверка работы фильтра по наличию товаров
status: pass

- summary: | # № 10 
    Проверка сброса фильтра по наличию товаров
status: fail

- summary: | # № 11 
    Проверка отображения подсказки значения поля минимальной цены фильтра по цене товаров
status: fail

- summary: | # № 12 
    Проверка отображения подсказки значения поля максимальной цены фильтра по цене товаров
status: fail

- summary: | # № 13 
    Проверка работы фильтра по минимальной цене товара
status: fail

- summary: | # № 14 
    Проверка работы фильтра по максимальной цене товара
status: fail

- summary: | # № 15 
    Проверка работы фильтра по минимальной и максимальной цене товара
status: fail

- summary: | # № 16 
    Проверка сброса фильтра по минимальной цене товара
status: pass

- summary: | # № 17 
    Проверка сброса фильтра по максимальной цене товара
status: pass

- summary: | # № 18 
    Проверка сброса фильтра по минимальной и максимальной цене товара
status: pass

- summary: | # № 19 
    Проверка отображения товаров каталога
status: pass

- summary: | # № 20 
    Проверка возможности просмотра карточки товара
status: pass

- summary: | # № 21 
    Проверка возможности перехода на следующую страницу каталога товаров
 status: pass

- summary: | # № 22 
    Проверка возможности перехода на предыдущую страницу каталога товаров
status: pass

- summary: | # № 23 
    Проверка отображения информации о товаре в каталоге товаров
status: fail

- summary: | # № 24 
    Проверка отображения информации о товаре в карточке товара
status: pass

- summary: | # № 25
    Проверка соответствия информации о товаре в каталоге с информацией в карточке товара
status: fail

- summary: | # № 26 
    Проверка расчета цены товара со скидкой в карточке товара
status: pass

- summary: | # № 27 
    Проверка добавления 1 единицы товара в корзину со страницы каталога
status: fail

- summary: | # № 28 
    Проверка добавления нескольких единиц товара в корзину со страницы каталога
status: fail

- summary: | # № 29 
    Проверка добавления нескольких товаров в корзину со страницы каталога
status: fail

- summary: | # № 30 
    Проверка добавления 1 единицы товара в корзину из карточки товара
status: fail

- summary: | # № 31 
    Проверка добавления нескольких единиц товара в корзину из карточки товара
status: fail

- summary: | # № 32 
    Проверка добавления нескольких товаров в корзину из карточек товаров
status: fail

- summary: | # № 33 
    Проверка возможности просмотра каталога товаров после добавления товара в корзину
status: pass

- summary: | # № 34 
    Проверка возможности просмотра каталога товаров из корзины после добавления товара
status: pass

- summary: | # № 35 
    Проверка удаления товара из корзины
status: pass

- summary: | # № 36 
    Проверка удаления нескольких единиц товара из корзины
status: fail

- summary: | # № 37
    Проверка удаления нескольких товаров из корзины
status: pass

- summary: | # № 38 
    Проверка очистки корзины
status: pass

- summary: | # № 39 
    Проверка перехода на страницу оплаты после оформления заказа
status: fail

- summary: | # № 40 
    Проверка хранения товаров в корзине в сессии браузера
status: fail

- summary: | # № 41 
    Проверка работы сайта в мобильной версии
status: pass
