---
- summary: | # № 1 
    Проверка отображения товаров первой страницы каталога при входе на сайт
  status: pass

- summary: | # № 2 
    Проверка отображения навигации по страницам на первой странице каталога товаров
  status: fail

- summary: | # № 3 
    Проверка отображения навигации по страницам на последней странице каталога товаров
  status: fail

- summary: | # № 4 
    Проверка отображения навигации по страницам на странице каталога товаров (кроме первой и последней)
  status: pass

- summary: | # № 5 
    Проверка перехода на страницу товара при нажатии на изображение товара на странице каталога
  status: pass

- summary: | # № 6 
    Проверка отображения товаров при переходе с первой страницы каталога на следующую
  status: pass

- summary: | # № 7 
    Проверка отображения товаров при переходе с последней страницы каталога на предыдущую
  status: fail

- summary: | # № 8 
    Проверка отображения информации о товарах на странице каталога
  status: fail

- summary: | # № 9 
    Проверка отображения информации о товаре на странице товара
  status: pass

- summary: | # № 10
    Проверка соответствия информации о товаре на странице каталога с информацией на странице товара
  status: fail

- summary: | # № 11
    Проверка расчета цены товара со скидкой на странице товара
  status: pass

- summary: | # № 12
    Проверка отображения товаров при поиске существующих товаров по ключевому слову
  status: pass

- summary: | # № 13
    Проверка отображения уведомления при поиске несуществующих товаров по ключевому слову
  status: pass

- summary: | # № 14 
    Проверка отображения товаров при очистке поля поиска фильтра по ключевому слову
  status: pass

- summary: | # № 15
    Проверка отображения товаров при выборе категории (кроме "пустой") в фильтре
  status: pass

- summary: | # № 16 
    Проверка отображения товаров при выборе "пустой" категории в фильтре
  status: fail

- summary: | # № 17 
    Проверка отображения товаров при выборе бренда в фильтре
  status: pass

- summary: | # № 18 
    Проверка отображения товаров при выборе нескольких брендов в фильтре
  status: pass

- summary: | # № 19
    Проверка отображения товаров при сбросе бренда в фильтре
  status: pass

- summary: | # № 20
    Проверка отображения товаров при сбросе 1 из выбранных брендов в фильтре
  status: pass

- summary: | # № 21 
    Проверка отображения товаров при выборе "В наличии" в фильтре
  status: pass

- summary: | # № 22 
    Проверка отображения товаров при сбросе "В наличии" в фильтре
  status: fail

- summary: | # № 23 
    Проверка отображения подсказки цены в поле минимального значения фильтра
  status: pass

- summary: | # № 24  
    Проверка отображения подсказки цены в поле максимального значения фильтра
  status: pass

- summary: | # № 25 
    Проверка отображения товаров при вводе максимального значения цены из диапазона х (x < цена самого дешевого товара) в поле минимального значения фильтра
  status: pass

- summary: | # № 26
    Проверка отображения товаров при вводе минимального значения цены из диапазона х (цена самого дешевого товара <= x < цена самого дорогого товара) в поле минимального значения фильтра
  status: pass

- summary: | # № 27 
    Проверка отображения товаров при вводе максимального значения цены из диапазона х (цена самого дешевого товара <= x < цена самого дорогого товара) в поле минимального значения фильтра
  status: pass

- summary: | # № 28
    Проверка отображения товаров при вводе минимального значения цены из диапазона х (цена самого дорогого товара <= х) в поле минимального значения фильтра
  status: pass

- summary: | # № 29
    Проверка отображения товаров при вводе максимального значения цены из диапазона х (x <= цена самого дешевого товара) в поле максимального значения фильтра
  status: pass

- summary: | # № 30
    Проверка отображения товаров при вводе минимального значения цены из диапазона х (цена самого дешевого товара < x <= цена самого дорогого товара) в поле максимального значения фильтра
  status: pass

- summary: | # № 31
    Проверка отображения товаров при вводе максимального значения цены из диапазона х (цена самого дешевого товара < x <= цена самого дорогого товара) в поле максимального значения фильтра
  status: pass

- summary: | # № 32
    Проверка отображения товаров при вводе минимального значения цены из диапазона х (цена самого дорогого товара < х) в поле максимального значения фильтра
  status: pass

- summary: | # № 33 
    Проверка отображения товаров при вводе цен в поля минимального и максимального значений фильтра
  status: pass

- summary: | # № 34 
    Проверка отображения товаров и подсказки цены поля при очистке поля минимального значения цены фильтра
  status: pass

- summary: | # № 35 
    Проверка отображения товаров и подсказки цены поля при очистке поля максимального значения цены фильтра
  status: pass

- summary: | # № 36 
    Проверка отображения товаров и подсказок цен полей при очистке полей минимального и максимального значений цен фильтра
  status: pass

- summary: | # № 37 
    Проверка значения счетчика корзины после добавления 1 единицы товара со страницы каталога
  status: pass

- summary: | # № 38 
    Проверка значения счетчика корзины после добавления нескольких единиц товара со страницы каталога
  status: pass

- summary: | # № 39 
    Проверка значения счетчика корзины после добавления нескольких товаров со страницы каталога
  status: pass

- summary: | # № 40 
    Проверка отображения товара и информации в корзине после добавления 1 единицы товара со страницы каталога
  status: pass

- summary: | # № 41 
    Проверка отображения товара и информации в корзине после добавления нескольких единиц товара со страницы каталога
  status: pass

- summary: | # № 42 
    Проверка отображения товаров и информации в корзине после добавления нескольких товаров со страницы каталога
  status: pass

- summary: | # № 43 
    Проверка значения счетчика корзины после добавления 1 единицы товара со страницы товара
  status: pass

- summary: | # № 44 
    Проверка значения счетчика корзины после добавления нескольких единиц товара со страницы товара
  status: pass

- summary: | # № 45 
    Проверка значения счетчика корзины после добавления нескольких товаров со страниц товаров
  status: pass

- summary: | # № 46 
    Проверка отображения товара и информации в корзине после добавления 1 единицы товара со страницы товара
  status: pass

- summary: | # № 47
    Проверка отображения товара и информации в корзине после добавления нескольких единиц товара со страницы товара
  status: pass

- summary: | # № 48 
    Проверка отображения товаров и информации в корзине после добавления нескольких товаров со страниц товаров
  status: pass

- summary: | # № 49 
    Проверка отображения товаров открытой страницы каталога после добавления товара в корзину
  status: pass

- summary: | # № 50 
    Проверка перехода на последнюю открытую страницу каталога и отображения товаров при выборе в корзине опции продолжения покупок
  status: pass

- summary: | # № 51 
    Проверка отсутствия товара и отображения информации в корзине после удаления добавленного товара
  status: pass

- summary: | # № 52 
    Проверка отсутствия товара и отображения информации в корзине после удаления всех единиц добавленного товара
  status: pass

- summary: | # № 53 
    Проверка отображения товара и информации в корзине после удаления 1 из нескольких единиц добавленного товара
  status: pass

- summary: | # № 54 
    Проверка отсутствия товаров и отображения информации в корзине после удаления нескольких добавленных товаров
  status: pass

- summary: | # № 55 
    Проверка отображения товара и информации в корзине после удаления 1 из 2 добавленных товаров
  status: pass

- summary: | # № 56 
    Проверка отсутствия товара и информации в корзине после очистки добавленного товара
  status: pass

- summary: | # № 57 
    Проверка отсутствия товара и информации в корзине после очистки нескольких единиц добавленного товара
  status: pass

- summary: | # № 58 
    Проверка отсутствия товаров и информации в корзине после очистки нескольких добавленных товаров
  status: pass

- summary: | # № 59 
    Проверка перехода на страницу оплаты после оформления заказа
  status: fail

- summary: | # № 60 
    Проверка хранения в сессии браузера товаров в корзине 
  status: fail

- summary: | # № 61 
    Проверка работы сайта в мобильной версии
  status: pass
