---
name: Anna Kotkova
job: QA Engineer
level: junior
email: msannicat@gmail.com
description: |
  Люблю тяжелую музыку и компьютерные игры.
  Люблю котов, белок и капибар.
  Хочу достойно зарабатывать, выучить английский и путешествовать.
skills:
  - функциональное тестирование
  - нефункциональное тестирование
  - написание баг-репортов
  - слепая печать на русском и английском языке
  - английский язык А1
